# Generated by Django 4.0.3 on 2022-11-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={},
        ),
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(max_length=250, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
